---
- name: deploy pyenv
  git:
    repo: git://github.com/pyenv/pyenv.git
    # Installation directory: @see http://www.itmedia.co.jp/help/howto/linux/0007master/14/04.html
    dest: /opt/pyenv

- name: install libselinux-python to set profile
  yum:
    name: libselinux-python

- name: arrow sudo for pyenv to execute pip by sudo when it's not Amazon Linux container
  replace:
    dest: /etc/sudoers
    regexp: '^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$'
    replace: 'Defaults    secure_path = /opt/pyenv/shims:/opt/pyenv/bin:/sbin:/bin:/usr/sbin:/usr/bin'
  when: '"container" not in group_names'

- name: set profile
  template:
    src: pyenv.sh.j2
    dest: /etc/profile.d/pyenv.sh
    owner: root
    group: root
    mode: 0644

# @see https://github.com/pyenv/pyenv/wiki/common-build-problems
- name: install dependencies to install python by pyenv for Fedora/CentOS/RHEL(aws ec2)
  yum:
    name:
      - make
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      # /opt/pyenv/plugins/python-build/bin/python-build: line 425: tar: command not found
      - tar

- name: install default python
  command: bash -lc 'pyenv install {{ python_pyenv_default_python_version }}'
  args:
    creates: /opt/pyenv/versions/{{ python_pyenv_default_python_version }}

- name: set default python version
  command: bash -lc 'pyenv global {{ python_pyenv_default_python_version }}'
