- hosts: default
  become: yes
  # ↓ Because Ansible 2.6.7 has bug that defaults is not detected.
  pre_tasks:
    - set_fact:
        python_install_pyenv: yes
      when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
    - set_fact:
        python_install_pyenv: no
      when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'sysvinit' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
  roles:
    - role: ansible-role-python2-amazon-linux
      vars:
        python_pyenv_default_python_version: 2.7.15
      tags:
        - pip
      when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
    - role: ansible-role-python2-amazon-linux
#      vars:
#        python_install_pyenv: no
      tags:
        - pip
      when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'sysvinit' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
    - role: ansible-role-guest-additions-centos
      tags:
        - guest-additions
    - role: ansible-role-kernel-devel-amazon-linux
      tags:
        - kernel-devel
    - role: ansible-role-cleaning-amazon-linux
      tags:
        - cleaning
