- hosts: default
  become: yes
  roles:
    - role: ansible-role-python-amazon-linux
      vars:
        pyenv_default_python_version: 2.7.12
      tags:
        - pip
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
    - role: ansible-role-python-amazon-linux
      vars:
        python_install_pyenv: no
      tags:
        - pip
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
#    - role: ansible-role-ansible-amazon-linux
#      tags:
#        - ansible
    - role: ansible-role-kernel-devel-amazon-linux
      tags:
        - kernel-devel
    - role: ansible-role-guest-additions-centos
      tags:
        - guest-additions
    - role: ansible-role-cleaning-amazon-linux
      tags:
        - cleaning
