---
- name: check whether pyenv is installed or not
  stat:
    path: /usr/local/pyenv
  register: stat_pyenv

- name: install Ansible
  pip:
    name: "{{ item }}"
    state: latest
    executable: "{{'/usr/local/pyenv/shims/pip' if stat_pyenv.stat.exists else '/bin/pip' }}"
  with_items:
    - ansible
    # ↓ for Ansible module "expect"
    - pexpect
