---
# @see https://askubuntu.com/questions/169024/how-can-i-tell-if-the-virtualbox-guest-additions-were-installed-on-an-ubuntu-vm
- name: check whether GuestAdditions is installed or not
  shell: lsmod | grep vboxguest
  register: module_guest_additions

- name: mount iso GuestAdditions
  mount:
    fstype: iso9660
    opts: loop
    path: /mnt
    src: /home/vagrant/VBoxGuestAdditions.iso
    state: mounted
  when: module_guest_additions.rc != 0

- name: install GuestAdditions
  command: /bin/sh -x /mnt/VBoxLinuxAdditions.run
  when: module_guest_additions.rc != 0

- name: unmount iso GuestAdditions
  mount:
    path: /mnt
    state: absent

- name: remove iso GuestAdditions
  file:
    path: /home/vagrant/VBoxGuestAdditions.iso
    state: absent
