---
- name: download pip installer
  uri:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    creates: /tmp/get-pip.py

- name: install pip
  command: bash -cl 'python /tmp/get-pip.py'
  args:
    creates: /usr/bin/pip

- name: Upgrade pip
  command: bash -cl 'python -m pip install --upgrade pip'
  