---
- name: update kernel-headers
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel
    - kernel-headers

- name: check current kernel version
  command: uname -r
  register: kernel_version

- name: install dependency of GuestAdditions
  yum:
    name: '{{ item }}'
  with_items:
    - gcc
    - make
    - perl
    - kernel-devel
#    - 'kernel-devel-{{ kernel_version.stdout }}'
