---
- name: update kernel-headers
  yum:
    name:
      - kernel
      - kernel-headers
    state: latest

- name: check updated kernel version
  shell: yum list installed | grep kernel.x86_64 | tail -n1 | awk '{print $2}'
  register: kernel_version

- name: install dependency of GuestAdditions
  yum:
    name:
      - gcc
      - make
      - perl
      - kernel-devel-{{ kernel_version.stdout }}

- name: ensure that kernel correctly installed
  file:
    path: /boot/initramfs-{{ kernel_version.stdout }}.x86_64.img
