---
- name: update kernel-headers
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel
    - kernel-headers

- name: check updated kernel version
  shell: yum list installed | grep kernel.x86_64 | tail -n1 | awk '{print $2}'
  register: kernel_version

- name: install dependency of GuestAdditions
  yum:
    name: '{{ item }}'
  with_items:
    - gcc
    - make
    - perl
    - 'kernel-devel-{{ kernel_version.stdout }}'
